implementation of awesome books using JS classes
ZahraArshia/awsome-books-project pull request #3
Opened 2022-02-15 14:44 UTC by ZahraArshia

2022-02-15 17:33 UTC, TedLivist requested changes
## STATUS: CHANGES REQUIRED ♻️ ♻️

Hi @ZahraArshia and @moise-mulungu,

Good job so far!
✔️ Books can be removed and added
✔️ The right book is removed when there are duplicates
However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-02-15 17:33 UTC, TedLivist commented on README.md
>  # Awesome books: plain JavaScript with objects
- [ ] In your README, kindly define instructions on how to get and run the app locally.

2022-02-15 17:33 UTC, TedLivist commented on index.html
> +<!-- <script src="./js/script.js"></script> -->
- [ ] Kindly remove commented code as they make your code look messy and hard to read

2022-02-16 08:17 UTC, ZahraArshia commented
Hello, thanks for the review
required changes implemented.

2022-02-16 08:20 UTC, rukundoeric approved these changes
Hi @ZahraArshia,

_Excellent job on this project. Keep it up 🎆_

_Congratulations! 🎉  on the splendid job 👍
You can now merge this PR and submit the project completion form 🚀 . I wish you all the very best in your next tasks 🥇_


Cheers and Happy coding!👏👏👏

__Feel free to leave any questions or comments in the PR thread if something is not 100% clear.__

------
>As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-02-16 08:31 UTC, merged